#!/bin/bash


function doItAll {
	dpath=

	if [[ $# -gt 0 ]]
	then
	    dpath=`dirname $1`'/'

		if [[ ! -d test_output_dir ]]
		then 
			mkdir test_output_dir
		fi

		#Construct auxilary samples
		echo "SAMPLE" > aux_samples.dat
		echo "Name smartsubmit" >> aux_samples.dat
		echo "Path $dpath" >> aux_samples.dat

		export CMS_PATH=/cvmfs/cms.cern.ch > /dev/null
		export SCRAM_ARCH=slc6_amd64_gcc491 > /dev/null
		source /cvmfs/cms.cern.ch/cmsset_default.sh > /dev/null


		pushd /cvmfs/cms.cern.ch/slc6_amd64_gcc491/cms/cmssw/CMSSW_7_4_1/src/ > /dev/null
		eval `scramv1 runtime -sh` > /dev/null
		popd > /dev/null

		cmsbin=/nfs-7/t2tas/Software/StopAnalysisCMSSW/src
		sabin=$cmsbin/StopAnalysis/StopBabyMaker

		export LD_LIBRARY_PATH=$sabin:$LD_LIBRARY_PATH
		#echo $LD_LIBRARY_PATH


		ln -s $sabin/json_files ./json_files
		ln -s $sabin/jecfiles ./jecfiles

		#ldd $sabin/runBabyMaker
		$sabin/runBabyMaker smartsubmit -1 -1 . aux_samples.dat

		mv smartsubmit.root baby1.root
		rm json_files
		rm jecfiles
		rm aux_samples.dat
	else
		echo "No files given"
	fi
}

doItAll $@